image: php:7.1

cache:
  paths:
    - vendor/

before_script:
  - apt-get update -yqq
  - apt-get install git -yqq

  - curl -sS https://getcomposer.org/installer | php
  - curl -O http://get.sensiolabs.org/sami.phar

  - php composer.phar install

stages:
  - test
  - docs
  - pages

test:
  script:
    - ./vendor/bin/phpunit --configuration ./config/phpunit.xml

docs:
  script:
    - php ./sami.phar update ./config/sami-config.php
  artifacts:
    paths:
      - docs
    expire_in: 20 minutes

pages:
  script:
    - mkdir -p ./public
    - ls -lha
    - cp ./docs/* ./public/
  artifacts:
    paths:
      - public
