image: php:7.1

cache:
  paths:
  - vendor/

before_script:
  - apt-get update -yqq
  - apt-get install git -yqq

  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install

stages:
  - test

test:
  script:
    - vendor/bin/phpunit --configuration config/phpunit.xml